# Generated by Django 3.1.2 on 2020-11-02 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharededit.chatroom')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharededit.chatuser')),
            ],
        ),
        migrations.AddField(
            model_name='chatuser',
            name='chat_rooms',
            field=models.ManyToManyField(through='sharededit.UserAndRoom', to='sharededit.ChatRoom'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='chat_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_users',
            field=models.ManyToManyField(through='sharededit.UserAndRoom', to='sharededit.ChatUser'),
        ),
    ]
